lock to specific tauri-cli version (#554)
Our GH actions failed to sign mac builds with:
```
   Compiling tauri-bundler v2.7.0
error[E0412]: cannot find type `Error` in crate `tauri_macos_sign`
   --> /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-bundler-2.7.0/src/error.rs:171:47
    |
171 |   AppleCodesign(#[from] Box<tauri_macos_sign::Error>),
    |                                               ^^^^^ not found in `tauri_macos_sign`
    |
help: consider importing one of these items
    |
  6 + use crate::Error;
    |
  6 + use crate::error::io::Error;
    |
  6 + use std::error::Error;
    |
  6 + use std::fmt::Error;
    |
    = and 22 other candidates
help: if you import `Error`, refer to it directly
    |
171 -   AppleCodesign(#[from] Box<tauri_macos_sign::Error>),
171 +   AppleCodesign(#[from] Box<Error>),
    |
   Compiling jsonrpsee-ws-client v0.24.9
   Compiling resvg v0.45.1
For more information about this error, try `rustc --explain E0412`.
error: could not compile `tauri-bundler` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tauri-cli v2.9.0`,
```
This is tracked in https://github.com/tauri-apps/tauri/issues/14335 and
should be solved in upstream. Until that happens we need to lock on
previous version.

Successful manual run after the change:
https://github.com/tempestteam/atlas/actions/runs/18683513031